### ISSUE TITLE
Don't open the `Edit` window by default

### ISSUE THREAD

**Issue by tkna91** [JoepVanlier/ysfx#48]
**Is your feature request related to a problem? Please describe.**

Sorry if I misunderstood something.
After displaying a plugin, the `Edit` window appears by default.
That window can only be closed after clicking the `Edit` button.

**Describe the solution you'd like**

I feel that the Edit window should be opened after the `Edit` button is clicked.

**Additional context**

Screencast:

https://github.com/user-attachments/assets/9e075bc9-457a-46d4-876a-681b6de4571a

Environment:
- OS: Arch Linux x86_64
- ysfx-s: [WIP version](https://github.com/JoepVanlier/ysfx/issues/44#issuecomment-2350342990)
- renoise 3.4.4-1
- sway-git 1.10.r7397.7288f77-1
- wlroots-git 0.19.0.r7218.54321088-1
- mesa 1:24.2.1-1
- linux 6.10.8.arch1-1

**Comment by JoepVanlier** [comment]
That's indeed a bug and I was already wondering about this behavior when I saw your previous screen grabs.

This might take a bit of figuring out. I hope you're up for testing a few builds with me as I cannot reproduce this locally.

Right now, my suspicion is that `setContentNonOwned` (that's where ysfx binds the IDE to that (then invisible) window) behaves differently on different platforms.

Alright, attempt 1: [Linux 64-bit VST3.zip](https://github.com/user-attachments/files/17002915/Linux.64-bit.VST3.zip).

**Comment by JoepVanlier** [comment]
Alright. If setting it to invisible doesn't work, then let's try just deferring the window entirely until you hit edit. Here is attempt number two: [Linux 64-bit VST3.zip](https://github.com/user-attachments/files/17003886/Linux.64-bit.VST3.zip)

**Comment by tkna91** [comment]
It works fine.

https://github.com/user-attachments/assets/15899720-21f5-4ff0-b2f8-66c778101bb8

You can close it as you wish, Thanks!

**Comment by JoepVanlier** [comment]
Wonderful. Glad to hear that.

Thanks for testing and please don't hesitate to report future bugs!

I'll do a few more tests and then make another quick pre-release, so that hopefully not too many people end up using the plugin with the old naming convention.
