### ISSUE TITLE
[BUG] All keys not working in Sequencer Megababy JS scripts

### ISSUE THREAD

**Issue by sollapse** [JoepVanlier/ysfx#55]
The sequencer megababy series of plugins do not work with the Ctrl key modifiers (tested in Ardour). Shift seems to work well.

**To Reproduce**
Load any of the sequencer megababy JS scripts, attempt to adjust the velocity of a note using the Ctrl+Left mouse drag.

**Expected behavior**
The velocity of the note should be altered.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11

**Comment by JoepVanlier** [comment]
Confirmed. Shouldn't be too hard to fix. Will report back when I tested the modifiers work correctly on all three platforms.

**Comment by JoepVanlier** [comment]
I opened a PR to fix this [here](https://github.com/JoepVanlier/ysfx/pull/56). Could you try the following and see if it works as intended? I'll wait with merging until you confirm that it works as intended.

[Windows 64-bit VST3.zip](https://github.com/user-attachments/files/17299883/Windows.64-bit.VST3.zip)

Do note that I do not yet support the windows key.

**Comment by sollapse** [comment]
It working as expected now. Thanks for the fix!

**Comment by JoepVanlier** [comment]
Great! I'll go ahead and merge it then! Thanks for the bug report and for reporting back!
